### ISSUE TITLE
Could you provide esm modules and source code without minification as in original ulid package as dist?

### ISSUE THREAD

**Issue by budarin** [perry-mitchell/ulidx#7]
I use only one method, but webpack could not do tree shaking on built common module - so the full package code is included in my app instead of some functions

**Comment by perry-mitchell** [comment]
Hi @budarin - You're right that currently ulidx is packaged as CJS, and this makes it impossible for webpack to treeshake.

Instead of providing a build where the output is just the source code, I would suggest that I support ECMAScript modules. I'd need to make sure that both the CJS and ESM builds can work together in the same package. I don't think publishing the Typescript source is a nice solution, I'd prefer to have to compiled to JS but retaining the module import/export approach.

**Comment by rockfreak** [comment]
This would be great if it was tree shakeable .

Can anyone help assist in this?

**Comment by perry-mitchell** [comment]
Currently working on an ESM-only build, which will probably be released as v1. It should be ready soon.

**Comment by bluet** [comment]
ref https://github.com/perry-mitchell/ulidx/pull/18

**Comment by perry-mitchell** [comment]
ESM+CJS now available in v1
